basePath: /api
definitions:
  markets.Market:
    properties:
      id:
        type: integer
      nameon:
        type: string
    type: object
  models.ArbitrageRow:
    properties:
      buy:
        type: number
      first_pay_type:
        type: string
      id:
        type: integer
      percent:
        type: number
      second_pay_type:
        type: string
      sell:
        type: number
    type: object
  models.CurrencyPair:
    properties:
      buy:
        type: string
      marketID:
        type: integer
      pair:
        type: string
      sell:
        type: string
      volume:
        type: string
    type: object
  models.P2PPair:
    properties:
      buy:
        type: string
      firstAsset:
        type: string
      marketId:
        type: integer
      payType:
        type: string
      secondAsset:
        type: string
      sell:
        type: string
    type: object
host: localhost:5050
info:
  contact: {}
  description: This is a docs for api
  title: Exchange-parser-server
  version: "1.0"
paths:
  /v1/arbitrage/rows:
    get:
      consumes:
      - application/json
      description: Get currency pair from all SPOT markets
      parameters:
      - description: offset
        example: 10
        in: query
        name: offset
        required: true
        type: integer
      - description: limit
        example: 10
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ArbitrageRow'
            type: array
      summary: Get currency pair
      tags:
      - Arbitrage
    post:
      consumes:
      - application/json
      description: replace all Arbitrage rows
      parameters:
      - description: arbitrage params
        in: body
        name: arbitrageRows
        required: true
        schema:
          items:
            $ref: '#/definitions/models.ArbitrageRow'
          type: array
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: replace all Arbitrage rows
      tags:
      - Arbitrage
  /v1/p2p/markets/all:
    get:
      consumes:
      - application/json
      description: Get all P2P markets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/markets.Market'
            type: array
      summary: Get all P2P markets
      tags:
      - P2P
  /v1/p2p/pair:
    get:
      consumes:
      - application/json
      description: Get p2p orders from all markets
      parameters:
      - description: Name of P2P pair
        example: USDT/P2PRUB
        in: query
        name: pair
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.P2PPair'
            type: array
      summary: Get
      tags:
      - P2P
  /v1/p2p/pairs/{marketP2PID}:
    get:
      consumes:
      - application/json
      description: Get all orders by market id
      parameters:
      - description: Name of SPOT pair
        in: path
        name: marketP2PID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.P2PPair'
            type: array
      summary: Get all
      tags:
      - P2P
  /v1/spot/markets/all:
    get:
      consumes:
      - application/json
      description: Get all SPOT markets
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/markets.Market'
            type: array
      summary: Get all
      tags:
      - SPOT
  /v1/spot/pair:
    get:
      consumes:
      - application/json
      description: Get currency pair from all SPOT markets
      parameters:
      - description: Name of SPOT pair
        example: BTCUSDT
        in: query
        name: pair
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.P2PPair'
            type: array
      summary: Get currency pair
      tags:
      - SPOT
  /v1/spot/pairs/{marketID}:
    get:
      consumes:
      - application/json
      description: Get all SPOT pairs by market id
      parameters:
      - description: SPOT market id
        in: path
        name: marketID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CurrencyPair'
            type: array
      summary: Get all
      tags:
      - SPOT
swagger: "2.0"
